[colors.primary]
background = "#242a2f"
foreground = "#ccbc9c"

[colors.cursor]
text = "#242a2f"
cursor = "#ccbc9c"

[colors.vi_mode_cursor]
text = "#242a2f"
cursor = "#ccbc9c"

[colors.search.matches]
foreground = "#242a2f"
background = "#ccbc9c"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#3d474c"
background = "#ccbc9c"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#242a2f"
red = "#e26c6e"
green = "#9db971"
yellow = "#d6b36e"
blue = "#71b3ab"
magenta = "#d089ab"
cyan = "#75b985"
white = "#ccbc9c"

[colors.bright]
black = "#3d474c"
red = "#e26c6e"
green = "#9db971"
yellow = "#d6b36e"
blue = "#71b3ab"
magenta = "#d089ab"
cyan = "#75b985"
white = "#ccbc9c"

[colors.dim]
black = "#ccbc9c"
red = "#e26c6e"
green = "#9db971"
yellow = "#d6b36e"
blue = "#71b3ab"
magenta = "#d089ab"
cyan = "#75b985"
white = "#3d474c"
