# Background and foreground colors
background = #242a2f
foreground = #ccbc9c

# Standard colors
palette = 0=#242a2f
palette = 1=#e26c6e
palette = 2=#9db971
palette = 3=#d6b36e
palette = 4=#71b3ab
palette = 5=#d089ab
palette = 6=#75b985
palette = 7=#ccbc9c

# Bright colors
palette = 8=#3d474c
palette = 9=#e26c6e
palette = 10=#9db971
palette = 11=#d6b36e
palette = 12=#71b3ab
palette = 13=#d089ab
palette = 14=#75b985
palette = 15=#ccbc9c
