background            #242a2f
foreground            #ccbc9c

# black
color0  #242a2f
color8  #3d474c

# red
color1  #e26c6e
color9  #e26c6e

# green
color2  #9db971
color10 #9db971

# yellow
color3  #d6b36e
color11 #d6b36e

# blue
color4  #71b3ab
color12 #71b3ab

# magenta
color5  #d089ab
color13 #d089ab

#cyan
color6  #75b985
color14 #75b985

#white
color7  #ccbc9c
color15 #ccbc9c


