# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 0
    # gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8

    blur {
        enabled = true
        size = 3
        passes = 2
        new_optimizations = true
        xray = false
    }
    blurls = waybar
    layerrule = blur,waybar
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

animations {
  enabled = 1
  bezier = liner, 1, 1, 1, 1
  bezier = ease, 0.5, 1.55, 1, 0.9
  animation = border, 1, 1, liner
  animation = borderangle, 1, 24, liner, loop
}

windowrule = bordercolor rgb(8ec07c) rgb(ebdbb2) 45deg focus:1
windowrulev2 = opacity 1.0 0.8,class:.*

layerrule = dimaround, walker
